var = [{'condition': 'is_dict', 'name': 'common', 'value': [{'condition': 'added', 'name': 'follow', 'value': False},
                                                            {'condition': 'related', 'name': 'setting1',
                                                             'value': 'Value 1'},
                                                            {'condition': 'removed', 'name': 'setting2', 'value': 200},
                                                            {'condition': 'changed_old', 'name': 'setting3',
                                                             'value': True},
                                                            {'condition': 'changed_new', 'name': 'setting3',
                                                             'value': None}, {'condition': 'added', 'name': 'setting4',
                                                                              'value': 'blah blah'},
                                                            {'condition': 'added', 'name': 'setting5',
                                                             'value': {'key5': 'value5'}},
                                                            {'condition': 'is_dict', 'name': 'setting6', 'value': [
                                                                {'condition': 'is_dict', 'name': 'doge', 'value': [
                                                                    {'condition': 'changed_old', 'name': 'wow',
                                                                     'value': ''},
                                                                    {'condition': 'changed_new', 'name': 'wow',
                                                                     'value': 'so much'}]},
                                                                {'condition': 'related', 'name': 'key',
                                                                 'value': 'value'},
                                                                {'condition': 'added', 'name': 'ops',
                                                                 'value': 'vops'}]}]},
       {'condition': 'is_dict', 'name': 'group1', 'value': [{'condition': 'changed_old', 'name': 'baz', 'value': 'bas'},
                                                            {'condition': 'changed_new', 'name': 'baz',
                                                             'value': 'bars'},
                                                            {'condition': 'related', 'name': 'foo', 'value': 'bar'},
                                                            {'condition': 'changed_old', 'name': 'nest',
                                                             'value': {'key': 'value'}},
                                                            {'condition': 'changed_new', 'name': 'nest',
                                                             'value': 'str'}]},
       {'condition': 'removed', 'name': 'group2', 'value': {'abc': 12345, 'deep': {'id': 45}}},
       {'condition': 'added', 'name': 'group3', 'value': {'deep': {'id': {'number': 45}}, 'fee': 100500}}]
